spring:
server:
   port: 8443
   ssl:
      key-store: classpath:localhost.p12
      key-store-password: byq2218283
      key-store-type: PKCS12
      key-alias: localhost
      
      trust-store: classpath:truststore.jks
      trust-store-password: byq2218283
      trust-store-type: JKS
      client-auth: need